apiVersion: app.boer.xyz/v1beta1
kind: AppService
metadata:
  name: whoami
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  size: 3
  image: traefik/whoami:latest
  ports:
    - port: 80
      targetPort: 80
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/whoami(/|$)(.*)"
            backend:
              service:
                name: whoami
                port:
                  number: 80